-- Migration: Add missing India ICMR micronutrient guidelines
-- This migration adds comprehensive micronutrient guidelines for India based on ICMR-NIN 2020 data
-- Includes infants, children, adolescents, adults with activity levels, elderly, pregnant and lactating women

-- Infants (0-6 months) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'common', 0, 0.5, 
 '{"iron": {"ai": null, "ul": 40, "rda": null, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 25, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 100, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 2, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 300, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.2, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 30, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 350, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 20, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 400, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 0.4, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 0.1, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 1.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Infants 0-6 months guidelines - Common', NOW(), NOW());

-- Infants (6-12 months) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'common', 0.5, 1, 
 '{"iron": {"ai": null, "ul": 40, "rda": 3, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 2.5, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 85, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 130, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 5, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 300, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.4, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 75, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 350, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 30, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 400, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 0.6, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 0.6, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 1.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Infants 6-12 months guidelines - Common', NOW(), NOW());

-- Children (1-3 years) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'common', 1, 3, 
 '{"iron": {"ai": null, "ul": 40, "rda": 8, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 3.3, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 120, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 90, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 7, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 500, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.7, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 90, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 390, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 30, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.1, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 0.9, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 1.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Children 1-3 years guidelines - Common', NOW(), NOW());

-- Children (4-6 years) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'common', 4, 6, 
 '{"iron": {"ai": null, "ul": 40, "rda": 11, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 4.5, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 135, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 90, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 9, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 550, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.9, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 125, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 510, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 35, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.3, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 1.2, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Children 4-6 years guidelines - Common', NOW(), NOW());

-- Children (7-9 years) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'common', 7, 9.99, 
 '{"iron": {"ai": null, "ul": 40, "rda": 15, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 5.9, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 170, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 90, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 11, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 650, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.1, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 175, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 630, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 45, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.6, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 1.5, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Children 7-9 years guidelines - Common', NOW(), NOW());

-- Boys (10-12 years)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'male', 10, 12, 
 '{"iron": {"ai": null, "ul": 45, "rda": 16, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 8.5, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 220, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 100, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 15, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 850, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.5, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 240, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 770, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 55, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 2.1, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 2, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Boys 10-12 years guidelines', NOW(), NOW());

-- Girls (10-12 years)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'female', 10, 12, 
 '{"iron": {"ai": null, "ul": 45, "rda": 28, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 8.5, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 225, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 100, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 14, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 850, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.4, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 250, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 790, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 50, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.9, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 1.9, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Girls 10-12 years guidelines', NOW(), NOW());

-- Boys (13-15 years)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'male', 13, 15, 
 '{"iron": {"ai": null, "ul": 45, "rda": 22, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 14.3, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 285, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 140, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 19, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.9, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 345, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 930, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 70, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 2.7, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 2.6, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Boys 13-15 years guidelines', NOW(), NOW());

-- Girls (13-15 years)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'female', 13, 15, 
 '{"iron": {"ai": null, "ul": 45, "rda": 30, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 12.8, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 245, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 140, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 16, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.6, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 340, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 890, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 65, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 2.2, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 2.2, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Girls 13-15 years guidelines', NOW(), NOW());

-- Boys (16-18 years)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'male', 16, 18.99, 
 '{"iron": {"ai": null, "ul": 45, "rda": 26, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 17.6, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 340, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 140, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 22, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 1050, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 2.2, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 440, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 1000, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 85, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 3.1, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 3, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Boys 16-18 years guidelines', NOW(), NOW());

-- Girls (16-18 years)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'female', 16, 18.99, 
 '{"iron": {"ai": null, "ul": 45, "rda": 32, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 14.2, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 270, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 140, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 17, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 1050, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.7, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 380, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 860, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 70, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 2.3, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 2.3, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Girls 16-18 years guidelines', NOW(), NOW());

-- Men (Sedentary) - 19-59 years
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'male', 19, 59.99, 
 '{"iron": {"ai": null, "ul": 45, "rda": 19, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 13, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 300, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 140, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 14, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.4, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 440, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 1000, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 80, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 2, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 1.9, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Men sedentary 19-59 years guidelines', NOW(), NOW());

-- Men (Moderate) - 19-59 years
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'male', 19, 59.99, 
 '{"iron": {"ai": null, "ul": 45, "rda": 19, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 13, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 300, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 140, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 18, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.8, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 440, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 1000, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 80, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 2.5, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 2.4, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Men moderate 19-59 years guidelines', NOW(), NOW());

-- Men (Heavy) - 19-59 years
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'male', 19, 59.99, 
 '{"iron": {"ai": null, "ul": 45, "rda": 19, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 13, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 300, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 140, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 23, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 2.3, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 440, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 1000, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 80, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 3.2, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 3.1, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Men heavy 19-59 years guidelines', NOW(), NOW());

-- Women (Sedentary) - 19-59 years
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'female', 19, 59.99, 
 '{"iron": {"ai": null, "ul": 45, "rda": 29, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 11, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 220, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 140, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 11, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.4, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 370, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 840, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 65, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.9, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 1.9, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Women sedentary 19-59 years guidelines', NOW(), NOW());

-- Women (Moderate) - 19-59 years
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'female', 19, 59.99, 
 '{"iron": {"ai": null, "ul": 45, "rda": 29, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 11, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 220, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 140, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 14, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.7, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 370, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 840, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 65, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 2.4, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 2.4, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Women moderate 19-59 years guidelines', NOW(), NOW());

-- Women (Heavy) - 19-59 years
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'female', 19, 59.99, 
 '{"iron": {"ai": null, "ul": 45, "rda": 29, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 11, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 220, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 140, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 18, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 2.2, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 370, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 840, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 65, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 3.1, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 2.4, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Women heavy 19-59 years guidelines', NOW(), NOW());

-- Men (≥60 years)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'male', 60, 120, 
 '{"iron": {"ai": null, "ul": 45, "rda": 19, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 13.2, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 300, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 140, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 14, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 1200, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.4, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 440, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 840, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 65, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 800, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 2, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 1.9, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Men ≥60 years guidelines', NOW(), NOW());

-- Women (≥60 years)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'female', 60, 120, 
 '{"iron": {"ai": null, "ul": 45, "rda": 19, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 13.2, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 200, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 140, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 11, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 1200, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.4, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 370, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 840, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 65, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 800, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.9, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 1.9, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Women ≥60 years guidelines', NOW(), NOW());

-- Pregnant Women (1st Trimester) - 19-50 years
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'female', 19, 50, 
 '{"iron": {"ai": null, "ul": 45, "rda": 27, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 14.5, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 570, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 220, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 2, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 440, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 900, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 80, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 2.7, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 2.3, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.45, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Pregnant women 1st trimester guidelines', NOW(), NOW());

-- Pregnant Women (2nd Trimester) - 19-50 years
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'female', 19, 50, 
 '{"iron": {"ai": null, "ul": 45, "rda": 27, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 14.5, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 570, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 220, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 2, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 440, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 900, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 80, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 2.7, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 2.3, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.45, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Pregnant women 2nd trimester guidelines', NOW(), NOW());

-- Pregnant Women (3rd Trimester) - 19-50 years
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'female', 19, 50, 
 '{"iron": {"ai": null, "ul": 45, "rda": 27, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 14.5, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 570, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 220, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 2, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 440, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 900, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 80, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 2.7, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 2.3, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.45, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Pregnant women 3rd trimester guidelines', NOW(), NOW());

-- Lactating Women (0-6 months) - 19-50 years
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'female', 19, 50, 
 '{"iron": {"ai": null, "ul": 45, "rda": 23, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 14.1, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 330, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 280, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 1200, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 2.1, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 400, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 950, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 115, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 3, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 2.37, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 3.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Lactating women 0-6 months guidelines', NOW(), NOW());

-- Lactating Women (7-12 months) - 19-50 years
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('India', 'female', 19, 50, 
 '{"iron": {"ai": null, "ul": 45, "rda": 23, "unit": "mg"}, "zinc": {"ai": null, "ul": null, "rda": 14.1, "unit": "mg"}, "biotin": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 330, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 280, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": null, "rda": 1200, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 2, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "magnesium": {"ai": null, "ul": null, "rda": 400, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 950, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 115, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 600, "unit": "IU"}, "vitamin_e": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 2.9, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 2.07, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 3.2, "unit": "mcg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": null, "unit": "mg"}}',
 'ICMR', 'ICMR-NIN', 2023, '', 'Lactating women 7-12 months guidelines', NOW(), NOW());
