-- Migration: Add missing USA DRI micronutrient guidelines
-- This migration adds comprehensive micronutrient guidelines for USA based on DRI Essential Guide data
-- Includes infants, children, adolescents, adults, elderly, pregnant and lactating women

-- Infants (0-6 months) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('USA', 'common', 0, 0.5, 
 '{"iron": {"ai": 0.27, "ul": 40, "rda": null, "unit": "mg"}, "zinc": {"ai": 2, "ul": 4, "rda": null, "unit": "mg"}, "biotin": {"ai": 5, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": 0.2, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": 65, "ul": null, "rda": null, "unit": "mcg"}, "iodine": {"ai": 110, "ul": null, "rda": null, "unit": "mcg"}, "niacin": {"ai": 2, "ul": null, "rda": null, "unit": "mg"}, "sodium": {"ai": 110, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": 200, "ul": 1000, "rda": null, "unit": "mg"}, "thiamin": {"ai": 0.2, "ul": null, "rda": null, "unit": "mg"}, "selenium": {"ai": 15, "ul": 45, "rda": null, "unit": "mcg"}, "magnesium": {"ai": 30, "ul": null, "rda": null, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": 400, "ul": 3000, "rda": null, "unit": "mcg"}, "vitamin_c": {"ai": 40, "ul": 2000, "rda": null, "unit": "mg"}, "vitamin_d": {"ai": 10, "ul": 100, "rda": null, "unit": "mcg"}, "vitamin_e": {"ai": 4, "ul": 1000, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": 2, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": 100, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": 0.3, "ul": null, "rda": null, "unit": "mg"}, "vitamin_b6": {"ai": 0.1, "ul": 100, "rda": null, "unit": "mg"}, "vitamin_b12": {"ai": 0.4, "ul": null, "rda": null, "unit": "mcg"}, "pantothenic_acid": {"ai": 1.7, "ul": null, "rda": null, "unit": "mg"}}',
 'US_DRI', 'DRI Essential Guide', 2020, '', 'Infants 0-6 months guidelines', NOW(), NOW());

-- Infants (7-12 months) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('USA', 'common', 0.5, 1, 
 '{"iron": {"ai": null, "ul": 40, "rda": 11, "unit": "mg"}, "zinc": {"ai": 3, "ul": 5, "rda": null, "unit": "mg"}, "biotin": {"ai": 6, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": 0.22, "ul": null, "rda": null, "unit": "mg"}, "folate": {"ai": 80, "ul": null, "rda": null, "unit": "mcg"}, "iodine": {"ai": 130, "ul": null, "rda": null, "unit": "mcg"}, "niacin": {"ai": 4, "ul": null, "rda": null, "unit": "mg"}, "sodium": {"ai": 370, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": 260, "ul": 1500, "rda": null, "unit": "mg"}, "thiamin": {"ai": 0.2, "ul": null, "rda": null, "unit": "mg"}, "selenium": {"ai": 20, "ul": 60, "rda": null, "unit": "mcg"}, "magnesium": {"ai": 75, "ul": null, "rda": null, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": 500, "ul": 3000, "rda": null, "unit": "mcg"}, "vitamin_c": {"ai": 50, "ul": 2000, "rda": null, "unit": "mg"}, "vitamin_d": {"ai": 10, "ul": 100, "rda": null, "unit": "mcg"}, "vitamin_e": {"ai": 5, "ul": 1000, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": 2.5, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": 275, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": 0.4, "ul": null, "rda": null, "unit": "mg"}, "vitamin_b6": {"ai": 0.3, "ul": 100, "rda": null, "unit": "mg"}, "vitamin_b12": {"ai": 0.5, "ul": null, "rda": null, "unit": "mcg"}, "pantothenic_acid": {"ai": 1.8, "ul": null, "rda": null, "unit": "mg"}}',
 'US_DRI', 'DRI Essential Guide', 2020, '', 'Infants 7-12 months guidelines', NOW(), NOW());

-- Children (1-3 years) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('USA', 'common', 1, 3.99, 
 '{"iron": {"ai": null, "ul": 40, "rda": 7, "unit": "mg"}, "zinc": {"ai": null, "ul": 7, "rda": 3, "unit": "mg"}, "biotin": {"ai": 8, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": 1, "rda": 0.34, "unit": "mg"}, "folate": {"ai": null, "ul": 300, "rda": 150, "unit": "mcg"}, "iodine": {"ai": null, "ul": 200, "rda": 90, "unit": "mcg"}, "niacin": {"ai": null, "ul": 10, "rda": 6, "unit": "mg"}, "sodium": {"ai": 1200, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": 2500, "rda": 700, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.5, "unit": "mg"}, "selenium": {"ai": null, "ul": 90, "rda": 20, "unit": "mcg"}, "magnesium": {"ai": null, "ul": 65, "rda": 80, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 600, "rda": 300, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": 400, "rda": 15, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": 100, "rda": 15, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": 200, "rda": 6, "unit": "mg"}, "vitamin_k": {"ai": 30, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": 3000, "rda": 460, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 0.5, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": 30, "rda": 0.5, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 0.9, "unit": "mcg"}, "pantothenic_acid": {"ai": 2, "ul": null, "rda": null, "unit": "mg"}}',
 'US_DRI', 'DRI Essential Guide', 2020, '', 'Children 1-3 years guidelines', NOW(), NOW());

-- Children (4-8 years) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('USA', 'common', 4, 8.99, 
 '{"iron": {"ai": null, "ul": 40, "rda": 10, "unit": "mg"}, "zinc": {"ai": null, "ul": 12, "rda": 5, "unit": "mg"}, "biotin": {"ai": 12, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": 3, "rda": 0.44, "unit": "mg"}, "folate": {"ai": null, "ul": 400, "rda": 200, "unit": "mcg"}, "iodine": {"ai": null, "ul": 300, "rda": 90, "unit": "mcg"}, "niacin": {"ai": null, "ul": 15, "rda": 8, "unit": "mg"}, "sodium": {"ai": 1500, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": 2500, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.6, "unit": "mg"}, "selenium": {"ai": null, "ul": 150, "rda": 30, "unit": "mcg"}, "magnesium": {"ai": null, "ul": 110, "rda": 130, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 900, "rda": 400, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": 650, "rda": 25, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": 100, "rda": 15, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": 300, "rda": 7, "unit": "mg"}, "vitamin_k": {"ai": 55, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": 3000, "rda": 500, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 0.6, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": 40, "rda": 0.6, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 1.2, "unit": "mcg"}, "pantothenic_acid": {"ai": 3, "ul": null, "rda": null, "unit": "mg"}}',
 'US_DRI', 'DRI Essential Guide', 2020, '', 'Children 4-8 years guidelines', NOW(), NOW());

-- Children (9-13 years) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('USA', 'common', 9, 13.99, 
 '{"iron": {"ai": null, "ul": 40, "rda": 8, "unit": "mg"}, "zinc": {"ai": null, "ul": 23, "rda": 8, "unit": "mg"}, "biotin": {"ai": 20, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": 5, "rda": 0.7, "unit": "mg"}, "folate": {"ai": null, "ul": 600, "rda": 300, "unit": "mcg"}, "iodine": {"ai": null, "ul": 600, "rda": 120, "unit": "mcg"}, "niacin": {"ai": null, "ul": 20, "rda": 12, "unit": "mg"}, "sodium": {"ai": 1800, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": 3000, "rda": 1300, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.9, "unit": "mg"}, "selenium": {"ai": null, "ul": 280, "rda": 40, "unit": "mcg"}, "magnesium": {"ai": null, "ul": 350, "rda": 240, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 1700, "rda": 600, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": 1200, "rda": 45, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": 100, "rda": 15, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": 600, "rda": 11, "unit": "mg"}, "vitamin_k": {"ai": 60, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": 4000, "rda": 1250, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 0.9, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": 60, "rda": 1.0, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 1.8, "unit": "mcg"}, "pantothenic_acid": {"ai": 4, "ul": null, "rda": null, "unit": "mg"}}',
 'US_DRI', 'DRI Essential Guide', 2020, '', 'Children 9-13 years guidelines', NOW(), NOW());

-- Adolescents (14-18 years) - Male
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('USA', 'male', 14, 18.99, 
 '{"iron": {"ai": null, "ul": 45, "rda": 11, "unit": "mg"}, "zinc": {"ai": null, "ul": 34, "rda": 11, "unit": "mg"}, "biotin": {"ai": 25, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": 8, "rda": 0.89, "unit": "mg"}, "folate": {"ai": null, "ul": 800, "rda": 400, "unit": "mcg"}, "iodine": {"ai": null, "ul": 900, "rda": 150, "unit": "mcg"}, "niacin": {"ai": null, "ul": 30, "rda": 16, "unit": "mg"}, "sodium": {"ai": 1500, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": 3000, "rda": 1300, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.2, "unit": "mg"}, "selenium": {"ai": null, "ul": 400, "rda": 55, "unit": "mcg"}, "magnesium": {"ai": null, "ul": 350, "rda": 410, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 2800, "rda": 900, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": 1800, "rda": 90, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": 100, "rda": 15, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": 800, "rda": 15, "unit": "mg"}, "vitamin_k": {"ai": 75, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": 4000, "rda": 1250, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.3, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": 80, "rda": 1.3, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.4, "unit": "mcg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}}',
 'US_DRI', 'DRI Essential Guide', 2020, '', 'Adolescents 14-18 years - Male guidelines', NOW(), NOW());

-- Adolescents (14-18 years) - Female
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('USA', 'female', 14, 18.99, 
 '{"iron": {"ai": null, "ul": 45, "rda": 15, "unit": "mg"}, "zinc": {"ai": null, "ul": 34, "rda": 9, "unit": "mg"}, "biotin": {"ai": 25, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": 8, "rda": 0.89, "unit": "mg"}, "folate": {"ai": null, "ul": 800, "rda": 400, "unit": "mcg"}, "iodine": {"ai": null, "ul": 900, "rda": 150, "unit": "mcg"}, "niacin": {"ai": null, "ul": 30, "rda": 14, "unit": "mg"}, "sodium": {"ai": 1500, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": 3000, "rda": 1300, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.0, "unit": "mg"}, "selenium": {"ai": null, "ul": 400, "rda": 55, "unit": "mcg"}, "magnesium": {"ai": null, "ul": 350, "rda": 360, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 2800, "rda": 700, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": 1800, "rda": 75, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": 100, "rda": 15, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": 800, "rda": 15, "unit": "mg"}, "vitamin_k": {"ai": 75, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": 4000, "rda": 1250, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.0, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": 80, "rda": 1.2, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.4, "unit": "mcg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}}',
 'US_DRI', 'DRI Essential Guide', 2020, '', 'Adolescents 14-18 years - Female guidelines', NOW(), NOW());

-- Adults (19-30 years) - Male
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('USA', 'male', 19, 30.99, 
 '{"iron": {"ai": null, "ul": 45, "rda": 8, "unit": "mg"}, "zinc": {"ai": null, "ul": 40, "rda": 11, "unit": "mg"}, "biotin": {"ai": 30, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": 10, "rda": 0.9, "unit": "mg"}, "folate": {"ai": null, "ul": 1000, "rda": 400, "unit": "mcg"}, "iodine": {"ai": null, "ul": 1100, "rda": 150, "unit": "mcg"}, "niacin": {"ai": null, "ul": 35, "rda": 16, "unit": "mg"}, "sodium": {"ai": 1500, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": 2500, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.2, "unit": "mg"}, "selenium": {"ai": null, "ul": 400, "rda": 55, "unit": "mcg"}, "magnesium": {"ai": null, "ul": 350, "rda": 400, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 3000, "rda": 900, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": 2000, "rda": 90, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": 100, "rda": 15, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": 1000, "rda": 15, "unit": "mg"}, "vitamin_k": {"ai": 120, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": 4000, "rda": 700, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.3, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": 100, "rda": 1.3, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.4, "unit": "mcg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}}',
 'US_DRI', 'DRI Essential Guide', 2020, '', 'Adults 19-30 years - Male guidelines', NOW(), NOW());

-- Adults (19-30 years) - Female
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('USA', 'female', 19, 30.99, 
 '{"iron": {"ai": null, "ul": 45, "rda": 18, "unit": "mg"}, "zinc": {"ai": null, "ul": 40, "rda": 8, "unit": "mg"}, "biotin": {"ai": 30, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": 10, "rda": 0.9, "unit": "mg"}, "folate": {"ai": null, "ul": 1000, "rda": 400, "unit": "mcg"}, "iodine": {"ai": null, "ul": 1100, "rda": 150, "unit": "mcg"}, "niacin": {"ai": null, "ul": 35, "rda": 14, "unit": "mg"}, "sodium": {"ai": 1500, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": 2500, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.1, "unit": "mg"}, "selenium": {"ai": null, "ul": 400, "rda": 55, "unit": "mcg"}, "magnesium": {"ai": null, "ul": 350, "rda": 310, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 3000, "rda": 700, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": 2000, "rda": 75, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": 100, "rda": 15, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": 1000, "rda": 15, "unit": "mg"}, "vitamin_k": {"ai": 90, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": 4000, "rda": 700, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.1, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": 100, "rda": 1.3, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.4, "unit": "mcg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}}',
 'US_DRI', 'DRI Essential Guide', 2020, '', 'Adults 19-30 years - Female guidelines', NOW(), NOW());

-- Adults (31-50 years) - Male
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('USA', 'male', 31, 50.99, 
 '{"iron": {"ai": null, "ul": 45, "rda": 8, "unit": "mg"}, "zinc": {"ai": null, "ul": 40, "rda": 11, "unit": "mg"}, "biotin": {"ai": 30, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": 10, "rda": 0.9, "unit": "mg"}, "folate": {"ai": null, "ul": 1000, "rda": 400, "unit": "mcg"}, "iodine": {"ai": null, "ul": 1100, "rda": 150, "unit": "mcg"}, "niacin": {"ai": null, "ul": 35, "rda": 16, "unit": "mg"}, "sodium": {"ai": 1500, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": 2500, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.2, "unit": "mg"}, "selenium": {"ai": null, "ul": 400, "rda": 55, "unit": "mcg"}, "magnesium": {"ai": null, "ul": 350, "rda": 420, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 3000, "rda": 900, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": 2000, "rda": 90, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": 100, "rda": 15, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": 1000, "rda": 15, "unit": "mg"}, "vitamin_k": {"ai": 120, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": 4000, "rda": 700, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.3, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": 100, "rda": 1.3, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.4, "unit": "mcg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}}',
 'US_DRI', 'DRI Essential Guide', 2020, '', 'Adults 31-50 years - Male guidelines', NOW(), NOW());

-- Adults (31-50 years) - Female
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('USA', 'female', 31, 50.99, 
 '{"iron": {"ai": null, "ul": 45, "rda": 18, "unit": "mg"}, "zinc": {"ai": null, "ul": 40, "rda": 8, "unit": "mg"}, "biotin": {"ai": 30, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": 10, "rda": 0.9, "unit": "mg"}, "folate": {"ai": null, "ul": 1000, "rda": 400, "unit": "mcg"}, "iodine": {"ai": null, "ul": 1100, "rda": 150, "unit": "mcg"}, "niacin": {"ai": null, "ul": 35, "rda": 14, "unit": "mg"}, "sodium": {"ai": 1500, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": 2500, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.1, "unit": "mg"}, "selenium": {"ai": null, "ul": 400, "rda": 55, "unit": "mcg"}, "magnesium": {"ai": null, "ul": 350, "rda": 320, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 3000, "rda": 700, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": 2000, "rda": 75, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": 100, "rda": 15, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": 1000, "rda": 15, "unit": "mg"}, "vitamin_k": {"ai": 90, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": 4000, "rda": 700, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.1, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": 100, "rda": 1.3, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.4, "unit": "mcg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}}',
 'US_DRI', 'DRI Essential Guide', 2020, '', 'Adults 31-50 years - Female guidelines', NOW(), NOW());

-- Adults (51-70 years) - Male
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('USA', 'male', 51, 70.99, 
 '{"iron": {"ai": null, "ul": 45, "rda": 8, "unit": "mg"}, "zinc": {"ai": null, "ul": 40, "rda": 11, "unit": "mg"}, "biotin": {"ai": 30, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": 10, "rda": 0.9, "unit": "mg"}, "folate": {"ai": null, "ul": 1000, "rda": 400, "unit": "mcg"}, "iodine": {"ai": null, "ul": 1100, "rda": 150, "unit": "mcg"}, "niacin": {"ai": null, "ul": 35, "rda": 16, "unit": "mg"}, "sodium": {"ai": 1300, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": 2000, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.2, "unit": "mg"}, "selenium": {"ai": null, "ul": 400, "rda": 55, "unit": "mcg"}, "magnesium": {"ai": null, "ul": 350, "rda": 420, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 3000, "rda": 900, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": 2000, "rda": 90, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": 100, "rda": 15, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": 1000, "rda": 15, "unit": "mg"}, "vitamin_k": {"ai": 120, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": 3000, "rda": 700, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.3, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": 100, "rda": 1.7, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.4, "unit": "mcg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}}',
 'US_DRI', 'DRI Essential Guide', 2020, '', 'Adults 51-70 years - Male guidelines', NOW(), NOW());

-- Adults (51-70 years) - Female
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('USA', 'female', 51, 70.99, 
 '{"iron": {"ai": null, "ul": 45, "rda": 8, "unit": "mg"}, "zinc": {"ai": null, "ul": 40, "rda": 8, "unit": "mg"}, "biotin": {"ai": 30, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": 10, "rda": 0.9, "unit": "mg"}, "folate": {"ai": null, "ul": 1000, "rda": 400, "unit": "mcg"}, "iodine": {"ai": null, "ul": 1100, "rda": 150, "unit": "mcg"}, "niacin": {"ai": null, "ul": 35, "rda": 14, "unit": "mg"}, "sodium": {"ai": 1300, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": 2000, "rda": 1200, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.1, "unit": "mg"}, "selenium": {"ai": null, "ul": 400, "rda": 55, "unit": "mcg"}, "magnesium": {"ai": null, "ul": 350, "rda": 320, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 3000, "rda": 700, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": 2000, "rda": 75, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": 100, "rda": 15, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": 1000, "rda": 15, "unit": "mg"}, "vitamin_k": {"ai": 90, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": 3000, "rda": 700, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.1, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": 100, "rda": 1.5, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.4, "unit": "mcg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}}',
 'US_DRI', 'DRI Essential Guide', 2020, '', 'Adults 51-70 years - Female guidelines', NOW(), NOW());

-- Elderly (>70 years) - Male
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('USA', 'male', 70, 120, 
 '{"iron": {"ai": null, "ul": 45, "rda": 8, "unit": "mg"}, "zinc": {"ai": null, "ul": 40, "rda": 11, "unit": "mg"}, "biotin": {"ai": 30, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": 10, "rda": 0.9, "unit": "mg"}, "folate": {"ai": null, "ul": 1000, "rda": 400, "unit": "mcg"}, "iodine": {"ai": null, "ul": 1100, "rda": 150, "unit": "mcg"}, "niacin": {"ai": null, "ul": 35, "rda": 16, "unit": "mg"}, "sodium": {"ai": 1200, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": 2000, "rda": 1200, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.2, "unit": "mg"}, "selenium": {"ai": null, "ul": 400, "rda": 55, "unit": "mcg"}, "magnesium": {"ai": null, "ul": 350, "rda": 420, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 3000, "rda": 900, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": 2000, "rda": 90, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": 100, "rda": 20, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": 1000, "rda": 15, "unit": "mg"}, "vitamin_k": {"ai": 120, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": 3000, "rda": 700, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.3, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": 100, "rda": 1.7, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.4, "unit": "mcg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}}',
 'US_DRI', 'DRI Essential Guide', 2020, '', 'Elderly >70 years - Male guidelines', NOW(), NOW());

-- Elderly (>70 years) - Female
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('USA', 'female', 70, 120, 
 '{"iron": {"ai": null, "ul": 45, "rda": 8, "unit": "mg"}, "zinc": {"ai": null, "ul": 40, "rda": 8, "unit": "mg"}, "biotin": {"ai": 30, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": 10, "rda": 0.9, "unit": "mg"}, "folate": {"ai": null, "ul": 1000, "rda": 400, "unit": "mcg"}, "iodine": {"ai": null, "ul": 1100, "rda": 150, "unit": "mcg"}, "niacin": {"ai": null, "ul": 35, "rda": 14, "unit": "mg"}, "sodium": {"ai": 1200, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": 2000, "rda": 1200, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.1, "unit": "mg"}, "selenium": {"ai": null, "ul": 400, "rda": 55, "unit": "mcg"}, "magnesium": {"ai": null, "ul": 350, "rda": 320, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 3000, "rda": 700, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": 2000, "rda": 75, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": 100, "rda": 20, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": 1000, "rda": 15, "unit": "mg"}, "vitamin_k": {"ai": 90, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": 3000, "rda": 700, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.1, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": 100, "rda": 1.5, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.4, "unit": "mcg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}}',
 'US_DRI', 'DRI Essential Guide', 2020, '', 'Elderly >70 years - Female guidelines', NOW(), NOW());

-- Pregnant Women (All trimesters) - 19-50 years
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('USA', 'female', 19, 50, 
 '{"iron": {"ai": null, "ul": 45, "rda": 27, "unit": "mg"}, "zinc": {"ai": null, "ul": 40, "rda": 11, "unit": "mg"}, "biotin": {"ai": 30, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": 10, "rda": 1.0, "unit": "mg"}, "folate": {"ai": null, "ul": 1000, "rda": 600, "unit": "mcg"}, "iodine": {"ai": null, "ul": 1100, "rda": 220, "unit": "mcg"}, "niacin": {"ai": null, "ul": 35, "rda": 18, "unit": "mg"}, "sodium": {"ai": 1500, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": 2500, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.4, "unit": "mg"}, "selenium": {"ai": null, "ul": 400, "rda": 60, "unit": "mcg"}, "magnesium": {"ai": null, "ul": 350, "rda": 360, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 3000, "rda": 770, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": 2000, "rda": 85, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": 100, "rda": 15, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": 1000, "rda": 15, "unit": "mg"}, "vitamin_k": {"ai": 90, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": 3500, "rda": 700, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.4, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": 100, "rda": 1.9, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.6, "unit": "mcg"}, "pantothenic_acid": {"ai": 6, "ul": null, "rda": null, "unit": "mg"}}',
 'US_DRI', 'DRI Essential Guide', 2020, '', 'Pregnant Women 19-50 years guidelines', NOW(), NOW());

-- Lactating Women (0-6 months) - 19-50 years
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('USA', 'female', 19, 50, 
 '{"iron": {"ai": null, "ul": 45, "rda": 9, "unit": "mg"}, "zinc": {"ai": null, "ul": 40, "rda": 12, "unit": "mg"}, "biotin": {"ai": 35, "ul": null, "rda": null, "unit": "mcg"}, "copper": {"ai": null, "ul": 10, "rda": 1.3, "unit": "mg"}, "folate": {"ai": null, "ul": 1000, "rda": 500, "unit": "mcg"}, "iodine": {"ai": null, "ul": 1100, "rda": 290, "unit": "mcg"}, "niacin": {"ai": null, "ul": 35, "rda": 17, "unit": "mg"}, "sodium": {"ai": 1500, "ul": null, "rda": null, "unit": "mg"}, "calcium": {"ai": null, "ul": 2500, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.4, "unit": "mg"}, "selenium": {"ai": null, "ul": 400, "rda": 70, "unit": "mcg"}, "magnesium": {"ai": null, "ul": 350, "rda": 320, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": null, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 3000, "rda": 1300, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": 2000, "rda": 120, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": 100, "rda": 15, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": 1000, "rda": 19, "unit": "mg"}, "vitamin_k": {"ai": 90, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": null, "ul": 3500, "rda": 700, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.6, "unit": "mg"}, "vitamin_b6": {"ai": null, "ul": 100, "rda": 2.0, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.8, "unit": "mcg"}, "pantothenic_acid": {"ai": 7, "ul": null, "rda": null, "unit": "mg"}}',
 'US_DRI', 'DRI Essential Guide', 2020, '', 'Lactating Women 0-6 months guidelines', NOW(), NOW());
