-- Migration: Add missing EU EFSA micronutrient guidelines
-- This migration adds comprehensive micronutrient guidelines for EU based on EFSA data
-- Includes infants, children, adolescents, adults, elderly, pregnant and lactating women
-- Source: EFSA's AR ↔ EAR and PRI ↔ RNI are conceptually equivalent but use EU terminology

-- Infants (7-11 months) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('EU', 'common', 0.58, 0.999, 
 '{"calcium": {"ai": 280, "ul": null, "rda": null, "unit": "mg"}, "chloride": {"ai": 0.3, "ul": null, "rda": null, "unit": "g"}, "copper": {"ai": 0.4, "ul": null, "rda": null, "unit": "mg"}, "fluoride": {"ai": 0.4, "ul": null, "rda": null, "unit": "mg"}, "iodine": {"ai": 70, "ul": null, "rda": null, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 11, "unit": "mg"}, "magnesium": {"ai": 80, "ul": null, "rda": null, "unit": "mg"}, "manganese": {"ai": 0.35, "ul": null, "rda": null, "unit": "mg"}, "molybdenum": {"ai": 10, "ul": null, "rda": null, "unit": "mcg"}, "phosphorus": {"ai": 160, "ul": null, "rda": null, "unit": "mg"}, "potassium": {"ai": 750, "ul": null, "rda": null, "unit": "mg"}, "selenium": {"ai": 15, "ul": 55, "rda": null, "unit": "mcg"}, "sodium": {"ai": 0.2, "ul": null, "rda": null, "unit": "g"}, "zinc": {"ai": null, "ul": null, "rda": 2.9, "unit": "mg"}, "biotin": {"ai": 6, "ul": null, "rda": null, "unit": "mcg"}, "choline": {"ai": 160, "ul": null, "rda": null, "unit": "mg"}, "cobalamin": {"ai": 1.5, "ul": null, "rda": null, "unit": "mcg"}, "folate": {"ai": 80, "ul": 200, "rda": null, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 1.6, "unit": "mg"}, "pantothenic_acid": {"ai": 3, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": 0.4, "ul": null, "rda": null, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.1, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 600, "rda": 250, "unit": "mcg"}, "vitamin_b6": {"ai": 0.3, "ul": 2.5, "rda": null, "unit": "mg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 20, "unit": "mg"}, "vitamin_d": {"ai": 10, "ul": 35, "rda": null, "unit": "mcg"}, "vitamin_e": {"ai": 5, "ul": 60, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": 10, "ul": null, "rda": null, "unit": "mcg"}}',
 'EU_EFSA', 'EFSA', 2023, '', 'Infants 7-11 months guidelines', NOW(), NOW());

-- Children (1-3 years) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('EU', 'common', 1, 3.99, 
 '{"calcium": {"ai": null, "ul": null, "rda": 450, "unit": "mg"}, "chloride": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "copper": {"ai": 0.85, "ul": 1, "rda": null, "unit": "mg"}, "fluoride": {"ai": 0.6, "ul": 1.5, "rda": null, "unit": "mg"}, "iodine": {"ai": 90, "ul": 200, "rda": null, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 7, "unit": "mg"}, "magnesium": {"ai": 200, "ul": 250, "rda": null, "unit": "mg"}, "manganese": {"ai": 0.5, "ul": null, "rda": null, "unit": "mg"}, "molybdenum": {"ai": 15, "ul": 0.1, "rda": null, "unit": "mg"}, "phosphorus": {"ai": 250, "ul": null, "rda": null, "unit": "mg"}, "potassium": {"ai": 800, "ul": null, "rda": null, "unit": "mg"}, "selenium": {"ai": 15, "ul": 70, "rda": null, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "zinc": {"ai": null, "ul": 7, "rda": 4.3, "unit": "mg"}, "biotin": {"ai": 20, "ul": null, "rda": null, "unit": "mcg"}, "choline": {"ai": 140, "ul": null, "rda": null, "unit": "mg"}, "cobalamin": {"ai": 1.5, "ul": null, "rda": null, "unit": "mcg"}, "folate": {"ai": null, "ul": 200, "rda": 120, "unit": "mcg"}, "niacin": {"ai": null, "ul": 150, "rda": 1.6, "unit": "mg"}, "pantothenic_acid": {"ai": 4, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 0.6, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.1, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 800, "rda": 250, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": 3.2, "rda": 0.6, "unit": "mg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 20, "unit": "mg"}, "vitamin_d": {"ai": 15, "ul": 50, "rda": null, "unit": "mcg"}, "vitamin_e": {"ai": 7.5, "ul": 100, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": 12, "ul": null, "rda": null, "unit": "mcg"}}',
 'EU_EFSA', 'EFSA', 2023, '', 'Children 1-3 years guidelines', NOW(), NOW());

-- Children (4-6 years) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('EU', 'common', 4, 6.99, 
 '{"calcium": {"ai": null, "ul": null, "rda": 800, "unit": "mg"}, "chloride": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "copper": {"ai": 1, "ul": 2, "rda": null, "unit": "mg"}, "fluoride": {"ai": 0.95, "ul": 2.5, "rda": null, "unit": "mg"}, "iodine": {"ai": 90, "ul": 250, "rda": null, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 7, "unit": "mg"}, "magnesium": {"ai": 230, "ul": 250, "rda": null, "unit": "mg"}, "manganese": {"ai": 1, "ul": null, "rda": null, "unit": "mg"}, "molybdenum": {"ai": 20, "ul": 0.2, "rda": null, "unit": "mg"}, "phosphorus": {"ai": 440, "ul": null, "rda": null, "unit": "mg"}, "potassium": {"ai": 1100, "ul": null, "rda": null, "unit": "mg"}, "selenium": {"ai": 20, "ul": 95, "rda": null, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "zinc": {"ai": null, "ul": 10, "rda": 5.5, "unit": "mg"}, "biotin": {"ai": 25, "ul": null, "rda": null, "unit": "mcg"}, "choline": {"ai": 170, "ul": null, "rda": null, "unit": "mg"}, "cobalamin": {"ai": 1.5, "ul": null, "rda": null, "unit": "mcg"}, "folate": {"ai": null, "ul": 300, "rda": 140, "unit": "mcg"}, "niacin": {"ai": null, "ul": 220, "rda": 1.6, "unit": "mg"}, "pantothenic_acid": {"ai": 4, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 0.7, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.1, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 1100, "rda": 300, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": 4.5, "rda": 0.7, "unit": "mg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 30, "unit": "mg"}, "vitamin_d": {"ai": 15, "ul": 50, "rda": null, "unit": "mcg"}, "vitamin_e": {"ai": 9, "ul": 120, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": 20, "ul": null, "rda": null, "unit": "mcg"}}',
 'EU_EFSA', 'EFSA', 2023, '', 'Children 4-6 years guidelines', NOW(), NOW());

-- Children (7-10 years) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('EU', 'common', 7, 10.99, 
 '{"calcium": {"ai": null, "ul": null, "rda": 800, "unit": "mg"}, "chloride": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "copper": {"ai": 1, "ul": 3, "rda": null, "unit": "mg"}, "fluoride": {"ai": 1.45, "ul": 2.5, "rda": null, "unit": "mg"}, "iodine": {"ai": 90, "ul": 300, "rda": null, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 11, "unit": "mg"}, "magnesium": {"ai": 230, "ul": 250, "rda": null, "unit": "mg"}, "manganese": {"ai": 1.5, "ul": null, "rda": null, "unit": "mg"}, "molybdenum": {"ai": 30, "ul": 0.25, "rda": null, "unit": "mg"}, "phosphorus": {"ai": 440, "ul": null, "rda": null, "unit": "mg"}, "potassium": {"ai": 1800, "ul": null, "rda": null, "unit": "mg"}, "selenium": {"ai": 35, "ul": 130, "rda": null, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "zinc": {"ai": null, "ul": 13, "rda": 7.4, "unit": "mg"}, "biotin": {"ai": 25, "ul": null, "rda": null, "unit": "mcg"}, "choline": {"ai": 250, "ul": null, "rda": null, "unit": "mcg"}, "cobalamin": {"ai": 2.5, "ul": null, "rda": null, "unit": "mcg"}, "folate": {"ai": null, "ul": 400, "rda": 200, "unit": "mcg"}, "niacin": {"ai": null, "ul": 350, "rda": 1.6, "unit": "mg"}, "pantothenic_acid": {"ai": 4, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.1, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 1500, "rda": 400, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": 6.1, "rda": 1, "unit": "mg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 45, "unit": "mg"}, "vitamin_d": {"ai": 15, "ul": 50, "rda": null, "unit": "mcg"}, "vitamin_e": {"ai": 9, "ul": 160, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": 30, "ul": null, "rda": null, "unit": "mcg"}}',
 'EU_EFSA', 'EFSA', 2023, '', 'Children 7-10 years guidelines', NOW(), NOW());

-- Children (11-14 years) - Male
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('EU', 'male', 11, 14.99, 
 '{"calcium": {"ai": null, "ul": null, "rda": 1150, "unit": "mg"}, "chloride": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "copper": {"ai": 1.3, "ul": 4, "rda": null, "unit": "mg"}, "fluoride": {"ai": 2.2, "ul": 5, "rda": null, "unit": "mg"}, "iodine": {"ai": 120, "ul": 450, "rda": null, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 11, "unit": "mg"}, "magnesium": {"ai": 300, "ul": 250, "rda": null, "unit": "mg"}, "manganese": {"ai": 2, "ul": null, "rda": null, "unit": "mg"}, "molybdenum": {"ai": 45, "ul": 0.4, "rda": null, "unit": "mg"}, "phosphorus": {"ai": 640, "ul": null, "rda": null, "unit": "mg"}, "potassium": {"ai": 2700, "ul": null, "rda": null, "unit": "mg"}, "selenium": {"ai": 55, "ul": 180, "rda": null, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "zinc": {"ai": null, "ul": 18, "rda": 10.7, "unit": "mg"}, "biotin": {"ai": 35, "ul": null, "rda": null, "unit": "mcg"}, "choline": {"ai": 340, "ul": null, "rda": null, "unit": "mcg"}, "cobalamin": {"ai": 3.5, "ul": null, "rda": null, "unit": "mcg"}, "folate": {"ai": null, "ul": 600, "rda": 270, "unit": "mcg"}, "niacin": {"ai": null, "ul": 500, "rda": 1.6, "unit": "mg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.4, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.1, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 2000, "rda": 600, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": 8.6, "rda": 1.4, "unit": "mg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 70, "unit": "mg"}, "vitamin_d": {"ai": 15, "ul": 100, "rda": null, "unit": "mcg"}, "vitamin_e": {"ai": 13, "ul": 220, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": 45, "ul": null, "rda": null, "unit": "mcg"}}',
 'EU_EFSA', 'EFSA', 2023, '', 'Children 11-14 years - Male guidelines', NOW(), NOW());

-- Children (11-14 years) - Female
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('EU', 'female', 11, 14.99, 
 '{"calcium": {"ai": null, "ul": null, "rda": 1150, "unit": "mg"}, "chloride": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "copper": {"ai": 1.1, "ul": 4, "rda": null, "unit": "mg"}, "fluoride": {"ai": 2.3, "ul": 5, "rda": null, "unit": "mg"}, "iodine": {"ai": 120, "ul": 450, "rda": null, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 13, "unit": "mg"}, "magnesium": {"ai": 250, "ul": 250, "rda": null, "unit": "mg"}, "manganese": {"ai": 2, "ul": null, "rda": null, "unit": "mg"}, "molybdenum": {"ai": 45, "ul": 0.4, "rda": null, "unit": "mg"}, "phosphorus": {"ai": 640, "ul": null, "rda": null, "unit": "mg"}, "potassium": {"ai": 2700, "ul": null, "rda": null, "unit": "mg"}, "selenium": {"ai": 55, "ul": 180, "rda": null, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "zinc": {"ai": null, "ul": 18, "rda": 10.7, "unit": "mg"}, "biotin": {"ai": 35, "ul": null, "rda": null, "unit": "mcg"}, "choline": {"ai": 340, "ul": null, "rda": null, "unit": "mcg"}, "cobalamin": {"ai": 3.5, "ul": null, "rda": null, "unit": "mcg"}, "folate": {"ai": null, "ul": 600, "rda": 270, "unit": "mcg"}, "niacin": {"ai": null, "ul": 500, "rda": 1.6, "unit": "mg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.4, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.1, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 2000, "rda": 600, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": 8.6, "rda": 1.4, "unit": "mg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 70, "unit": "mg"}, "vitamin_d": {"ai": 15, "ul": 100, "rda": null, "unit": "mcg"}, "vitamin_e": {"ai": 11, "ul": 220, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": 45, "ul": null, "rda": null, "unit": "mcg"}}',
 'EU_EFSA', 'EFSA', 2023, '', 'Children 11-14 years - Female guidelines', NOW(), NOW());

-- Children (15-17 years) - Male
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('EU', 'male', 15, 17.99, 
 '{"calcium": {"ai": null, "ul": null, "rda": 1150, "unit": "mg"}, "chloride": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "copper": {"ai": 1.3, "ul": 4, "rda": null, "unit": "mg"}, "fluoride": {"ai": 3.2, "ul": 7, "rda": null, "unit": "mg"}, "iodine": {"ai": 130, "ul": 500, "rda": null, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 11, "unit": "mg"}, "magnesium": {"ai": 300, "ul": 250, "rda": null, "unit": "mg"}, "manganese": {"ai": 3, "ul": null, "rda": null, "unit": "mg"}, "molybdenum": {"ai": 65, "ul": 0.5, "rda": null, "unit": "mg"}, "phosphorus": {"ai": 640, "ul": null, "rda": null, "unit": "mg"}, "potassium": {"ai": 3500, "ul": null, "rda": null, "unit": "mg"}, "selenium": {"ai": 70, "ul": 230, "rda": null, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "zinc": {"ai": null, "ul": 22, "rda": 14.2, "unit": "mg"}, "biotin": {"ai": 35, "ul": null, "rda": null, "unit": "mcg"}, "choline": {"ai": 400, "ul": null, "rda": null, "unit": "mcg"}, "cobalamin": {"ai": 4, "ul": null, "rda": null, "unit": "mcg"}, "folate": {"ai": null, "ul": 800, "rda": 330, "unit": "mcg"}, "niacin": {"ai": null, "ul": 700, "rda": 1.6, "unit": "mg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.6, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.1, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 2600, "rda": 750, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": 10.7, "rda": 1.7, "unit": "mg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 100, "unit": "mg"}, "vitamin_d": {"ai": 15, "ul": 100, "rda": null, "unit": "mcg"}, "vitamin_e": {"ai": 13, "ul": 260, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": 65, "ul": null, "rda": null, "unit": "mcg"}}',
 'EU_EFSA', 'EFSA', 2023, '', 'Children 15-17 years - Male guidelines', NOW(), NOW());

-- Children (15-17 years) - Female
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('EU', 'female', 15, 17.99, 
 '{"calcium": {"ai": null, "ul": null, "rda": 1150, "unit": "mg"}, "chloride": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "copper": {"ai": 1.1, "ul": 4, "rda": null, "unit": "mg"}, "fluoride": {"ai": 2.8, "ul": 7, "rda": null, "unit": "mg"}, "iodine": {"ai": 130, "ul": 500, "rda": null, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 13, "unit": "mg"}, "magnesium": {"ai": 250, "ul": 250, "rda": null, "unit": "mg"}, "manganese": {"ai": 3, "ul": null, "rda": null, "unit": "mg"}, "molybdenum": {"ai": 65, "ul": 0.5, "rda": null, "unit": "mg"}, "phosphorus": {"ai": 640, "ul": null, "rda": null, "unit": "mg"}, "potassium": {"ai": 3500, "ul": null, "rda": null, "unit": "mg"}, "selenium": {"ai": 70, "ul": 230, "rda": null, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "zinc": {"ai": null, "ul": 22, "rda": 11.9, "unit": "mg"}, "biotin": {"ai": 35, "ul": null, "rda": null, "unit": "mcg"}, "choline": {"ai": 400, "ul": null, "rda": null, "unit": "mcg"}, "cobalamin": {"ai": 4, "ul": null, "rda": null, "unit": "mcg"}, "folate": {"ai": null, "ul": 800, "rda": 330, "unit": "mcg"}, "niacin": {"ai": null, "ul": 700, "rda": 1.6, "unit": "mg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.6, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.1, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 2600, "rda": 650, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": 10.7, "rda": 1.6, "unit": "mg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 90, "unit": "mg"}, "vitamin_d": {"ai": 15, "ul": 100, "rda": null, "unit": "mcg"}, "vitamin_e": {"ai": 11, "ul": 260, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": 65, "ul": null, "rda": null, "unit": "mcg"}}',
 'EU_EFSA', 'EFSA', 2023, '', 'Children 15-17 years - Female guidelines', NOW(), NOW());

-- Adults (18-24 years) - Male
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('EU', 'male', 18, 24.99, 
 '{"calcium": {"ai": null, "ul": 2500, "rda": 1000, "unit": "mg"}, "chloride": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "copper": {"ai": 1.6, "ul": 5, "rda": null, "unit": "mg"}, "fluoride": {"ai": 3.4, "ul": 7, "rda": null, "unit": "mg"}, "iodine": {"ai": 150, "ul": 600, "rda": null, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 11, "unit": "mg"}, "magnesium": {"ai": 350, "ul": 250, "rda": null, "unit": "mg"}, "manganese": {"ai": 3, "ul": null, "rda": null, "unit": "mg"}, "molybdenum": {"ai": 65, "ul": 0.6, "rda": null, "unit": "mg"}, "phosphorus": {"ai": 550, "ul": null, "rda": null, "unit": "mg"}, "potassium": {"ai": 3500, "ul": null, "rda": null, "unit": "mg"}, "selenium": {"ai": 70, "ul": 255, "rda": null, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "zinc": {"ai": null, "ul": 25, "rda": 9.4, "unit": "mg"}, "biotin": {"ai": 40, "ul": null, "rda": null, "unit": "mcg"}, "choline": {"ai": 400, "ul": null, "rda": null, "unit": "mcg"}, "cobalamin": {"ai": 4, "ul": null, "rda": null, "unit": "mcg"}, "folate": {"ai": null, "ul": 1000, "rda": 330, "unit": "mcg"}, "niacin": {"ai": null, "ul": 900, "rda": 1.6, "unit": "mg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.6, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.1, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 3000, "rda": 750, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": 12, "rda": 1.7, "unit": "mg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 110, "unit": "mg"}, "vitamin_d": {"ai": 15, "ul": 100, "rda": null, "unit": "mcg"}, "vitamin_e": {"ai": 13, "ul": 300, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": 70, "ul": null, "rda": null, "unit": "mcg"}}',
 'EU_EFSA', 'EFSA', 2023, '', 'Adults 18-24 years - Male guidelines', NOW(), NOW());

-- Adults (18-24 years) - Female
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('EU', 'female', 18, 24.99, 
 '{"calcium": {"ai": null, "ul": 2500, "rda": 1000, "unit": "mg"}, "chloride": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "copper": {"ai": 1.3, "ul": 5, "rda": null, "unit": "mg"}, "fluoride": {"ai": 2.9, "ul": 7, "rda": null, "unit": "mg"}, "iodine": {"ai": 150, "ul": 600, "rda": null, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 16, "unit": "mg"}, "magnesium": {"ai": 300, "ul": 250, "rda": null, "unit": "mg"}, "manganese": {"ai": 3, "ul": null, "rda": null, "unit": "mg"}, "molybdenum": {"ai": 65, "ul": 0.6, "rda": null, "unit": "mg"}, "phosphorus": {"ai": 550, "ul": null, "rda": null, "unit": "mg"}, "potassium": {"ai": 3500, "ul": null, "rda": null, "unit": "mg"}, "selenium": {"ai": 70, "ul": 255, "rda": null, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "zinc": {"ai": null, "ul": 25, "rda": 7.5, "unit": "mg"}, "biotin": {"ai": 40, "ul": null, "rda": null, "unit": "mcg"}, "choline": {"ai": 400, "ul": null, "rda": null, "unit": "mcg"}, "cobalamin": {"ai": 4, "ul": null, "rda": null, "unit": "mcg"}, "folate": {"ai": null, "ul": 1000, "rda": 330, "unit": "mcg"}, "niacin": {"ai": null, "ul": 900, "rda": 1.6, "unit": "mg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.6, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.1, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 3000, "rda": 650, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": 12, "rda": 1.6, "unit": "mg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 95, "unit": "mg"}, "vitamin_d": {"ai": 15, "ul": 100, "rda": null, "unit": "mcg"}, "vitamin_e": {"ai": 11, "ul": 300, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": 70, "ul": null, "rda": null, "unit": "mcg"}}',
 'EU_EFSA', 'EFSA', 2023, '', 'Adults 18-24 years - Female guidelines', NOW(), NOW());

-- Adults (25+ years) - Male
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('EU', 'male', 25, 120, 
 '{"calcium": {"ai": null, "ul": 2500, "rda": 950, "unit": "mg"}, "chloride": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "copper": {"ai": 1.6, "ul": 5, "rda": null, "unit": "mg"}, "fluoride": {"ai": 3.4, "ul": 7, "rda": null, "unit": "mg"}, "iodine": {"ai": 150, "ul": 600, "rda": null, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 11, "unit": "mg"}, "magnesium": {"ai": 350, "ul": 250, "rda": null, "unit": "mg"}, "manganese": {"ai": 3, "ul": null, "rda": null, "unit": "mg"}, "molybdenum": {"ai": 65, "ul": 0.6, "rda": null, "unit": "mg"}, "phosphorus": {"ai": 550, "ul": null, "rda": null, "unit": "mg"}, "potassium": {"ai": 3500, "ul": null, "rda": null, "unit": "mg"}, "selenium": {"ai": 70, "ul": 255, "rda": null, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "zinc": {"ai": null, "ul": 25, "rda": 9.4, "unit": "mg"}, "biotin": {"ai": 40, "ul": null, "rda": null, "unit": "mcg"}, "choline": {"ai": 400, "ul": null, "rda": null, "unit": "mcg"}, "cobalamin": {"ai": 4, "ul": null, "rda": null, "unit": "mcg"}, "folate": {"ai": null, "ul": 1000, "rda": 330, "unit": "mcg"}, "niacin": {"ai": null, "ul": 900, "rda": 1.6, "unit": "mg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.6, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.1, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 3000, "rda": 750, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": 12, "rda": 1.7, "unit": "mg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 110, "unit": "mg"}, "vitamin_d": {"ai": 15, "ul": 100, "rda": null, "unit": "mcg"}, "vitamin_e": {"ai": 13, "ul": 300, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": 70, "ul": null, "rda": null, "unit": "mcg"}}',
 'EU_EFSA', 'EFSA', 2023, '', 'Adults 25+ years - Male guidelines', NOW(), NOW());

-- Adults (25+ years) - Female
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('EU', 'female', 25, 120, 
 '{"calcium": {"ai": null, "ul": 2500, "rda": 950, "unit": "mg"}, "chloride": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "copper": {"ai": 1.3, "ul": 5, "rda": null, "unit": "mg"}, "fluoride": {"ai": 2.9, "ul": 7, "rda": null, "unit": "mg"}, "iodine": {"ai": 150, "ul": 600, "rda": null, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 11, "unit": "mg"}, "magnesium": {"ai": 300, "ul": 250, "rda": null, "unit": "mg"}, "manganese": {"ai": 3, "ul": null, "rda": null, "unit": "mg"}, "molybdenum": {"ai": 65, "ul": 0.6, "rda": null, "unit": "mg"}, "phosphorus": {"ai": 550, "ul": null, "rda": null, "unit": "mg"}, "potassium": {"ai": 3500, "ul": null, "rda": null, "unit": "mg"}, "selenium": {"ai": 70, "ul": 255, "rda": null, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "zinc": {"ai": null, "ul": 25, "rda": 7.5, "unit": "mg"}, "biotin": {"ai": 40, "ul": null, "rda": null, "unit": "mcg"}, "choline": {"ai": 400, "ul": null, "rda": null, "unit": "mcg"}, "cobalamin": {"ai": 4, "ul": null, "rda": null, "unit": "mcg"}, "folate": {"ai": null, "ul": 1000, "rda": 330, "unit": "mcg"}, "niacin": {"ai": null, "ul": 900, "rda": 1.6, "unit": "mg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.6, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.1, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 3000, "rda": 650, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": 12, "rda": 1.6, "unit": "mg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 95, "unit": "mg"}, "vitamin_d": {"ai": 15, "ul": 100, "rda": null, "unit": "mcg"}, "vitamin_e": {"ai": 11, "ul": 300, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": 70, "ul": null, "rda": null, "unit": "mcg"}}',
 'EU_EFSA', 'EFSA', 2023, '', 'Adults 25+ years - Female guidelines', NOW(), NOW());

-- Pregnant Women (≥18 years) - Female
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('EU', 'female', 18, 120, 
 '{"calcium": {"ai": null, "ul": 2500, "rda": 1000, "unit": "mg"}, "chloride": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "copper": {"ai": 1.5, "ul": 5, "rda": null, "unit": "mg"}, "fluoride": {"ai": 2.9, "ul": 7, "rda": null, "unit": "mg"}, "iodine": {"ai": 200, "ul": 600, "rda": null, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 16, "unit": "mg"}, "magnesium": {"ai": 300, "ul": 250, "rda": null, "unit": "mg"}, "manganese": {"ai": 3, "ul": null, "rda": null, "unit": "mg"}, "molybdenum": {"ai": 65, "ul": 0.6, "rda": null, "unit": "mg"}, "phosphorus": {"ai": 550, "ul": null, "rda": null, "unit": "mg"}, "potassium": {"ai": 3500, "ul": null, "rda": null, "unit": "mg"}, "selenium": {"ai": 70, "ul": 255, "rda": null, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "zinc": {"ai": null, "ul": 25, "rda": 8.8, "unit": "mg"}, "biotin": {"ai": 40, "ul": null, "rda": null, "unit": "mcg"}, "choline": {"ai": 480, "ul": null, "rda": null, "unit": "mcg"}, "cobalamin": {"ai": 4.5, "ul": null, "rda": null, "unit": "mcg"}, "folate": {"ai": 600, "ul": 1000, "rda": null, "unit": "mcg"}, "niacin": {"ai": null, "ul": 900, "rda": 1.6, "unit": "mg"}, "pantothenic_acid": {"ai": 5, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.9, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.1, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 3000, "rda": 700, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": 12, "rda": 1.8, "unit": "mg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 105, "unit": "mg"}, "vitamin_d": {"ai": 15, "ul": 100, "rda": null, "unit": "mcg"}, "vitamin_e": {"ai": 11, "ul": 300, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": 70, "ul": null, "rda": null, "unit": "mcg"}}',
 'EU_EFSA', 'EFSA', 2023, '', 'Pregnant Women ≥18 years guidelines', NOW(), NOW());

-- Lactating Women (≥18 years) - Female
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('EU', 'female', 18, 120, 
 '{"calcium": {"ai": null, "ul": 2500, "rda": 1000, "unit": "mg"}, "chloride": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "copper": {"ai": 1.5, "ul": 5, "rda": null, "unit": "mg"}, "fluoride": {"ai": 2.9, "ul": 7, "rda": null, "unit": "mg"}, "iodine": {"ai": 200, "ul": 600, "rda": null, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 16, "unit": "mg"}, "magnesium": {"ai": 300, "ul": 250, "rda": null, "unit": "mg"}, "manganese": {"ai": 3, "ul": null, "rda": null, "unit": "mg"}, "molybdenum": {"ai": 65, "ul": 0.6, "rda": null, "unit": "mg"}, "phosphorus": {"ai": 550, "ul": null, "rda": null, "unit": "mg"}, "potassium": {"ai": 4000, "ul": null, "rda": null, "unit": "mg"}, "selenium": {"ai": 85, "ul": 255, "rda": null, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": null, "unit": "g"}, "zinc": {"ai": null, "ul": 25, "rda": 10.4, "unit": "mg"}, "biotin": {"ai": 45, "ul": null, "rda": null, "unit": "mcg"}, "choline": {"ai": 520, "ul": null, "rda": null, "unit": "mcg"}, "cobalamin": {"ai": 5, "ul": null, "rda": null, "unit": "mcg"}, "folate": {"ai": null, "ul": 1000, "rda": 500, "unit": "mcg"}, "niacin": {"ai": null, "ul": 900, "rda": 1.6, "unit": "mg"}, "pantothenic_acid": {"ai": 7, "ul": null, "rda": null, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 2, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.1, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": 3000, "rda": 1300, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": 12, "rda": 1.7, "unit": "mg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 155, "unit": "mg"}, "vitamin_d": {"ai": 15, "ul": 100, "rda": null, "unit": "mcg"}, "vitamin_e": {"ai": 11, "ul": 300, "rda": null, "unit": "mg"}, "vitamin_k": {"ai": 70, "ul": null, "rda": null, "unit": "mcg"}}',
 'EU_EFSA', 'EFSA', 2023, '', 'Lactating Women ≥18 years guidelines', NOW(), NOW());
