-- Migration: Add missing WHO/FAO micronutrient guidelines
-- This migration adds comprehensive micronutrient guidelines for WHO/FAO based on 2004 data
-- Includes infants, children, adolescents, adults, pregnant and lactating women
-- Source: WHO/FAO 2004 Human Vitamin and Mineral Requirements

-- Infants (0-6 months) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('WHO', 'common', 0, 0.5, 
 '{"biotin": {"ai": null, "ul": null, "rda": 5, "unit": "mcg"}, "calcium": {"ai": null, "ul": null, "rda": 300, "unit": "mg"}, "choline": {"ai": null, "ul": null, "rda": 125, "unit": "mg"}, "chromium": {"ai": null, "ul": null, "rda": 0.2, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": 0.2, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 65, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 90, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 0.3, "unit": "mg"}, "magnesium": {"ai": null, "ul": null, "rda": 26, "unit": "mg"}, "manganese": {"ai": null, "ul": null, "rda": 0.0003, "unit": "mg"}, "molybdenum": {"ai": null, "ul": null, "rda": 5, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 2, "unit": "mg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": 1.7, "unit": "mg"}, "phosphorus": {"ai": null, "ul": null, "rda": 100, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": 400, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 0.3, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": 6, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": 120, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.2, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 375, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 0.1, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 0.4, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 25, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 5, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": null, "rda": 4, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": 5, "unit": "mcg"}, "zinc": {"ai": null, "ul": null, "rda": 2, "unit": "mg"}}',
 'WHO_FAO', 'WHO/FAO 2004', 2004, '', 'Infants 0-6 months guidelines', NOW(), NOW());

-- Infants (7-12 months) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('WHO', 'common', 0.5, 0.999, 
 '{"biotin": {"ai": null, "ul": null, "rda": 6, "unit": "mcg"}, "calcium": {"ai": null, "ul": null, "rda": 400, "unit": "mg"}, "choline": {"ai": null, "ul": null, "rda": 150, "unit": "mg"}, "chromium": {"ai": null, "ul": null, "rda": 0.4, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": 0.3, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 80, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 90, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 9.3, "unit": "mg"}, "magnesium": {"ai": null, "ul": null, "rda": 54, "unit": "mg"}, "manganese": {"ai": null, "ul": null, "rda": 0.001, "unit": "mg"}, "molybdenum": {"ai": null, "ul": null, "rda": 10, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 4, "unit": "mg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": 1.8, "unit": "mg"}, "phosphorus": {"ai": null, "ul": null, "rda": 275, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": 700, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 0.4, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": 10, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": 370, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.3, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 400, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 0.3, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 0.7, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 30, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 5, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": null, "rda": 5, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": 10, "unit": "mcg"}, "zinc": {"ai": null, "ul": null, "rda": 3, "unit": "mg"}}',
 'WHO_FAO', 'WHO/FAO 2004', 2004, '', 'Infants 7-12 months guidelines', NOW(), NOW());

-- Children (1-3 years) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('WHO', 'common', 1, 3.99, 
 '{"biotin": {"ai": null, "ul": null, "rda": 8, "unit": "mcg"}, "calcium": {"ai": null, "ul": null, "rda": 500, "unit": "mg"}, "choline": {"ai": null, "ul": null, "rda": 200, "unit": "mg"}, "chromium": {"ai": null, "ul": null, "rda": 11, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": 0.4, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 100, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 90, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 5.8, "unit": "mg"}, "magnesium": {"ai": null, "ul": null, "rda": 60, "unit": "mg"}, "manganese": {"ai": null, "ul": null, "rda": 0.5, "unit": "mg"}, "molybdenum": {"ai": null, "ul": null, "rda": 17, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 6, "unit": "mg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": 2, "unit": "mg"}, "phosphorus": {"ai": null, "ul": null, "rda": 460, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": 3000, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 0.5, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": 17, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": 1000, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.5, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 400, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 0.5, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 0.9, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 30, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 5, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": null, "rda": 6, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": 15, "unit": "mcg"}, "zinc": {"ai": null, "ul": null, "rda": 4, "unit": "mg"}}',
 'WHO_FAO', 'WHO/FAO 2004', 2004, '', 'Children 1-3 years guidelines', NOW(), NOW());

-- Children (4-6 years) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('WHO', 'common', 4, 6.99, 
 '{"biotin": {"ai": null, "ul": null, "rda": 12, "unit": "mcg"}, "calcium": {"ai": null, "ul": null, "rda": 600, "unit": "mg"}, "choline": {"ai": null, "ul": null, "rda": 250, "unit": "mg"}, "chromium": {"ai": null, "ul": null, "rda": 15, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": 0.6, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 150, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 90, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 6.3, "unit": "mg"}, "magnesium": {"ai": null, "ul": null, "rda": 76, "unit": "mg"}, "manganese": {"ai": null, "ul": null, "rda": 1, "unit": "mg"}, "molybdenum": {"ai": null, "ul": null, "rda": 22, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 8, "unit": "mg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": 3, "unit": "mg"}, "phosphorus": {"ai": null, "ul": null, "rda": 500, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": 3800, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 0.6, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": 22, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": 1200, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.6, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 450, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 0.6, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 1.2, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 30, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 5, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": null, "rda": 7, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": 20, "unit": "mcg"}, "zinc": {"ai": null, "ul": null, "rda": 5, "unit": "mg"}}',
 'WHO_FAO', 'WHO/FAO 2004', 2004, '', 'Children 4-6 years guidelines', NOW(), NOW());

-- Children (7-9 years) - Common (same for both genders)
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('WHO', 'common', 7, 9.99, 
 '{"biotin": {"ai": null, "ul": null, "rda": 20, "unit": "mcg"}, "calcium": {"ai": null, "ul": null, "rda": 700, "unit": "mg"}, "choline": {"ai": null, "ul": null, "rda": 375, "unit": "mg"}, "chromium": {"ai": null, "ul": null, "rda": 20, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": 0.7, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 200, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 120, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 8.9, "unit": "mg"}, "magnesium": {"ai": null, "ul": null, "rda": 100, "unit": "mg"}, "manganese": {"ai": null, "ul": null, "rda": 1.5, "unit": "mg"}, "molybdenum": {"ai": null, "ul": null, "rda": 28, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 12, "unit": "mg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": 4, "unit": "mg"}, "phosphorus": {"ai": null, "ul": null, "rda": 800, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": 4500, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 0.9, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": 21, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": 1500, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 0.9, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 500, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 1, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 1.8, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 35, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 5, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": null, "rda": 8, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": 25, "unit": "mcg"}, "zinc": {"ai": null, "ul": null, "rda": 7, "unit": "mg"}}',
 'WHO_FAO', 'WHO/FAO 2004', 2004, '', 'Children 7-9 years guidelines', NOW(), NOW());

-- Adolescents (10-12 years) - Male
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('WHO', 'male', 10, 12.99, 
 '{"biotin": {"ai": null, "ul": null, "rda": 25, "unit": "mcg"}, "calcium": {"ai": null, "ul": null, "rda": 1300, "unit": "mg"}, "choline": {"ai": null, "ul": null, "rda": 425, "unit": "mg"}, "chromium": {"ai": null, "ul": null, "rda": 25, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": 0.9, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 300, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 120, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 14.6, "unit": "mg"}, "magnesium": {"ai": null, "ul": null, "rda": 230, "unit": "mg"}, "manganese": {"ai": null, "ul": null, "rda": 2, "unit": "mg"}, "molybdenum": {"ai": null, "ul": null, "rda": 34, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 16, "unit": "mg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": 5, "unit": "mg"}, "phosphorus": {"ai": null, "ul": null, "rda": 1150, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": 4500, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.3, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": 32, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": 1500, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.2, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 600, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 1.3, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 1.8, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 40, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 5, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": null, "rda": 10, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": 45, "unit": "mcg"}, "zinc": {"ai": null, "ul": null, "rda": 9, "unit": "mg"}}',
 'WHO_FAO', 'WHO/FAO 2004', 2004, '', 'Adolescents 10-12 years - Male guidelines', NOW(), NOW());

-- Adolescents (10-12 years) - Female
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('WHO', 'female', 10, 12.99, 
 '{"biotin": {"ai": null, "ul": null, "rda": 25, "unit": "mcg"}, "calcium": {"ai": null, "ul": null, "rda": 1300, "unit": "mg"}, "choline": {"ai": null, "ul": null, "rda": 425, "unit": "mg"}, "chromium": {"ai": null, "ul": null, "rda": 25, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": 0.9, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 300, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 120, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 14, "unit": "mg"}, "magnesium": {"ai": null, "ul": null, "rda": 220, "unit": "mg"}, "manganese": {"ai": null, "ul": null, "rda": 2, "unit": "mg"}, "molybdenum": {"ai": null, "ul": null, "rda": 34, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 16, "unit": "mg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": 5, "unit": "mg"}, "phosphorus": {"ai": null, "ul": null, "rda": 1150, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": 4500, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": 26, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": 1500, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.1, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 600, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 1.2, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 1.8, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 40, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 5, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": null, "rda": 10, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": 45, "unit": "mcg"}, "zinc": {"ai": null, "ul": null, "rda": 8, "unit": "mg"}}',
 'WHO_FAO', 'WHO/FAO 2004', 2004, '', 'Adolescents 10-12 years - Female guidelines', NOW(), NOW());

-- Adolescents (13-15 years) - Male
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('WHO', 'male', 13, 15.999, 
 '{"biotin": {"ai": null, "ul": null, "rda": 25, "unit": "mcg"}, "calcium": {"ai": null, "ul": null, "rda": 1300, "unit": "mg"}, "choline": {"ai": null, "ul": null, "rda": 550, "unit": "mg"}, "chromium": {"ai": null, "ul": null, "rda": 30, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": 1, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 400, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 150, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 18.8, "unit": "mg"}, "magnesium": {"ai": null, "ul": null, "rda": 230, "unit": "mg"}, "manganese": {"ai": null, "ul": null, "rda": 2.5, "unit": "mg"}, "molybdenum": {"ai": null, "ul": null, "rda": 43, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 16, "unit": "mg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": 5, "unit": "mg"}, "phosphorus": {"ai": null, "ul": null, "rda": 1250, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": 4700, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.3, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": 32, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": 1500, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.2, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 900, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 1.3, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 40, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 5, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": null, "rda": 12, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": 55, "unit": "mcg"}, "zinc": {"ai": null, "ul": null, "rda": 11, "unit": "mg"}}',
 'WHO_FAO', 'WHO/FAO 2004', 2004, '', 'Adolescents 13-15 years - Male guidelines', NOW(), NOW());

-- Adolescents (13-15 years) - Female
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('WHO', 'female', 13, 15.999, 
 '{"biotin": {"ai": null, "ul": null, "rda": 25, "unit": "mcg"}, "calcium": {"ai": null, "ul": null, "rda": 1300, "unit": "mg"}, "choline": {"ai": null, "ul": null, "rda": 550, "unit": "mg"}, "chromium": {"ai": null, "ul": null, "rda": 30, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": 1, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 400, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 150, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 31, "unit": "mg"}, "magnesium": {"ai": null, "ul": null, "rda": 220, "unit": "mg"}, "manganese": {"ai": null, "ul": null, "rda": 2.5, "unit": "mg"}, "molybdenum": {"ai": null, "ul": null, "rda": 43, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 16, "unit": "mg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": 5, "unit": "mg"}, "phosphorus": {"ai": null, "ul": null, "rda": 1250, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": 4700, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": 26, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": 1500, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.1, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 800, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 1.2, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 40, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 5, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": null, "rda": 12, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": 55, "unit": "mcg"}, "zinc": {"ai": null, "ul": null, "rda": 9, "unit": "mg"}}',
 'WHO_FAO', 'WHO/FAO 2004', 2004, '', 'Adolescents 13-15 years - Female guidelines', NOW(), NOW());

-- Adults (19-50 years) - Male
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('WHO', 'male', 19, 50.99, 
 '{"biotin": {"ai": null, "ul": null, "rda": 30, "unit": "mcg"}, "calcium": {"ai": null, "ul": null, "rda": 1000, "unit": "mg"}, "choline": {"ai": null, "ul": null, "rda": 550, "unit": "mg"}, "chromium": {"ai": null, "ul": null, "rda": 35, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": 1.2, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 400, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 150, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 13.7, "unit": "mg"}, "magnesium": {"ai": null, "ul": null, "rda": 260, "unit": "mg"}, "manganese": {"ai": null, "ul": null, "rda": 3, "unit": "mg"}, "molybdenum": {"ai": null, "ul": null, "rda": 45, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 16, "unit": "mg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": 5, "unit": "mg"}, "phosphorus": {"ai": null, "ul": null, "rda": 580, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": 4700, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.3, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": 34, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": 1500, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.2, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 900, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 1.3, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.4, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 45, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 5, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": null, "rda": 10, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": 65, "unit": "mcg"}, "zinc": {"ai": null, "ul": null, "rda": 11, "unit": "mg"}}',
 'WHO_FAO', 'WHO/FAO 2004', 2004, '', 'Adults 19-50 years - Male guidelines', NOW(), NOW());

-- Adults (19-50 years) - Female
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('WHO', 'female', 19, 50.99, 
 '{"biotin": {"ai": null, "ul": null, "rda": 30, "unit": "mcg"}, "calcium": {"ai": null, "ul": null, "rda": 1000, "unit": "mg"}, "choline": {"ai": null, "ul": null, "rda": 425, "unit": "mg"}, "chromium": {"ai": null, "ul": null, "rda": 35, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": 1.2, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 400, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 150, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 29.4, "unit": "mg"}, "magnesium": {"ai": null, "ul": null, "rda": 220, "unit": "mg"}, "manganese": {"ai": null, "ul": null, "rda": 3, "unit": "mg"}, "molybdenum": {"ai": null, "ul": null, "rda": 45, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 14, "unit": "mg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": 5, "unit": "mg"}, "phosphorus": {"ai": null, "ul": null, "rda": 580, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": 4700, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.1, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": 26, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": 1500, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.1, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 700, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 1.3, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.4, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 45, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 5, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": null, "rda": 10, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": 55, "unit": "mcg"}, "zinc": {"ai": null, "ul": null, "rda": 8, "unit": "mg"}}',
 'WHO_FAO', 'WHO/FAO 2004', 2004, '', 'Adults 19-50 years - Female guidelines', NOW(), NOW());

-- Pregnant Women (≥18 years) - Female
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('WHO', 'female', 18, 120, 
 '{"biotin": {"ai": null, "ul": null, "rda": 30, "unit": "mcg"}, "calcium": {"ai": null, "ul": null, "rda": 1300, "unit": "mg"}, "choline": {"ai": null, "ul": null, "rda": 450, "unit": "mg"}, "chromium": {"ai": null, "ul": null, "rda": 35, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": 1.3, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 600, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 200, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 29.4, "unit": "mg"}, "magnesium": {"ai": null, "ul": null, "rda": 355, "unit": "mg"}, "manganese": {"ai": null, "ul": null, "rda": 3, "unit": "mg"}, "molybdenum": {"ai": null, "ul": null, "rda": 50, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 18, "unit": "mg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": 6, "unit": "mg"}, "phosphorus": {"ai": null, "ul": null, "rda": 580, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": 4700, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.4, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": 60, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": 1500, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.4, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 800, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 1.9, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.6, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 55, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 5, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": null, "rda": 9, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": 65, "unit": "mcg"}, "zinc": {"ai": null, "ul": null, "rda": 11, "unit": "mg"}}',
 'WHO_FAO', 'WHO/FAO 2004', 2004, '', 'Pregnant Women ≥18 years guidelines', NOW(), NOW());

-- Lactating Women (≥18 years) - Female
INSERT INTO micronutrient_guidelines_flexible (country, gender, age_min, age_max, micronutrients, guideline_type, source, source_year, version, notes, created_at, updated_at)
VALUES 
('WHO', 'female', 18, 120, 
 '{"biotin": {"ai": null, "ul": null, "rda": 35, "unit": "mcg"}, "calcium": {"ai": null, "ul": null, "rda": 1000, "unit": "mg"}, "choline": {"ai": null, "ul": null, "rda": 550, "unit": "mg"}, "chromium": {"ai": null, "ul": null, "rda": 35, "unit": "mcg"}, "copper": {"ai": null, "ul": null, "rda": 1.3, "unit": "mg"}, "folate": {"ai": null, "ul": null, "rda": 500, "unit": "mcg"}, "iodine": {"ai": null, "ul": null, "rda": 200, "unit": "mcg"}, "iron": {"ai": null, "ul": null, "rda": 29.4, "unit": "mg"}, "magnesium": {"ai": null, "ul": null, "rda": 390, "unit": "mg"}, "manganese": {"ai": null, "ul": null, "rda": 3, "unit": "mg"}, "molybdenum": {"ai": null, "ul": null, "rda": 50, "unit": "mcg"}, "niacin": {"ai": null, "ul": null, "rda": 17, "unit": "mg"}, "pantothenic_acid": {"ai": null, "ul": null, "rda": 7, "unit": "mg"}, "phosphorus": {"ai": null, "ul": null, "rda": 580, "unit": "mg"}, "potassium": {"ai": null, "ul": null, "rda": 4700, "unit": "mg"}, "riboflavin": {"ai": null, "ul": null, "rda": 1.6, "unit": "mg"}, "selenium": {"ai": null, "ul": null, "rda": 70, "unit": "mcg"}, "sodium": {"ai": null, "ul": null, "rda": 1500, "unit": "mg"}, "thiamin": {"ai": null, "ul": null, "rda": 1.5, "unit": "mg"}, "vitamin_a": {"ai": null, "ul": null, "rda": 950, "unit": "mcg"}, "vitamin_b6": {"ai": null, "ul": null, "rda": 2, "unit": "mg"}, "vitamin_b12": {"ai": null, "ul": null, "rda": 2.8, "unit": "mcg"}, "vitamin_c": {"ai": null, "ul": null, "rda": 70, "unit": "mg"}, "vitamin_d": {"ai": null, "ul": null, "rda": 5, "unit": "mcg"}, "vitamin_e": {"ai": null, "ul": null, "rda": 11, "unit": "mg"}, "vitamin_k": {"ai": null, "ul": null, "rda": 65, "unit": "mcg"}, "zinc": {"ai": null, "ul": null, "rda": 12, "unit": "mg"}}',
 'WHO_FAO', 'WHO/FAO 2004', 2004, '', 'Lactating Women ≥18 years guidelines', NOW(), NOW());
